WHITESPACE = _{ " " | "\t" | "\n" }
COMMENT = _{ "//" ~ (!"\n" ~ ANY)* ~ "\n" }

program = { SOI ~ statement* ~ EOI }
statement = { (var_decl | expr) ~ semicolon }

var_decl = { "let" ~ identifier ~ "=" ~ expr }
identifier = @{ ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_")* }
expr = { term ~ ((add | multiply) ~ term)* }
term = { number | identifier }

number = @{ ASCII_DIGIT+ }
add = { "+" }
multiply = { "*" }
semicolon = { ";" }