[package]
name = "x-debugger"
edition.workspace = true
version.workspace = true

[dependencies]
clap = { workspace = true, features = ["derive"] }
console = "0.16.0"
indicatif = "0.18.0"
similar = "2.7.0"
